### ISSUE TITLE
Separate `here`/`latest`/etc needed?

### ISSUE THREAD

**Issue by mitchblank** [fuzzballcat/milliForth#2]
Sorry if I'm not understanding something after only a quick glance at the code.

My understanding of the goal is that you want to make `sector.asm` as small as possible by moving any not-strictly-needed functionality into `hello_world.FORTH` instead, correct?

Currently there are four assembly-implemented tokens that just expose the address of variables inside of the assembly kernel: `state`, `>in`, `here`, `latest`

Could instead the assembly just define a single data structure?  i.e. the equivalent of C...
```c
struct state_block {
    uint16_t state;  // 0 = compile words, 1 = execute words
    uint16_t cin;
    uint16_t here;
    uint16_t latest;
};
```
...and then just park the whole thing at `0x1000`?

Then you could just define `state` in assembly and do the rest with:
```forth
: cin state 2 + ;
: here cin 2 + ;
: latest here 2 + ;
```

Or if you want to be really extreme and just consider the `0x1000` a well-known constant just have the forth code synthesize it itself:
```forth
: state 80h 2* 2* 2* 2* 2* ;
```

**Comment by fuzzballcat** [comment]
No, good thinking!  Sometimes you get pigeonholed into one way of thinking and unconsciously ignore a good idea...

I'll mess with this in a bit and see if I run into any issues, but I suspect you can get rid of at least a few of the variables.

Note that I don't want to park everything at `0x1000` and rely on "well-known constant", since for some reason that feels like cheating.  (But `tib` at `0x0000` isn't?  Well me, I'll have to think about it.)

**Comment by fuzzballcat** [comment]
I've implemented this.  Thanks for the suggestion!
