### ISSUE TITLE
no license?

### ISSUE THREAD

**Issue by Jan69** [fuzzballcat/milliForth#4]
https://choosealicense.com/no-permission/
**most places default to _All Rights Reserved_ by default**, so unless you add a license, it would likely be illegal for people to do ANYTHING with it, 
> Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

**Comment by Jan69** [comment]
if it's intentional, please clarify that, if it's not, then there's plenty of very permissive licenses, or even just public domain

**Comment by fuzzballcat** [comment]
Hah, yeah I definitely do not intend to be fully restrictive, I think that would actually be _wrong_ given how much of an inspiration sectorFORTH has been.

Now that I look at it, I'm actually a little wary to put my own license on this — since I'm technically distributing a "modified version" of the hello world example included with sectorFORTH, which would fall under sectorFORTH's license, right?  So maybe I need to put my own license and sectorFORTH's license together... or maybe I'm being too defensive here.  I'm frankly fairly new to this.

**Comment by fuzzballcat** [comment]
Okay, I've added an MIT License.  If anyone sees that I've done something wrong, please let me know.
