### ISSUE TITLE
] word

### ISSUE THREAD

**Issue by farvardin** [fuzzballcat/milliForth#5]
hello,

When using the python script to autotype in qemu, it seems to get stuck after the compilation of the 27th line: 
`: ] 0 state@ ! ;`

then I couldn't type anything else, qemu seems to hang.   (I've then modified the script to stop just before the `;` to check how it would crash just after I've typed the last `;`)

(using qemu 6.2.0 on Linux Mint / Debian)

**Comment by fuzzballcat** [comment]
Hmm.  Unfortunately, I don't have access to a Linux system, so I can't seem to reproduce this issue.

_However_, I have had issues with pyautogui sometimes typing garbage characters (sometimes invisible!) for no apparent reason.  If this is the root of the problem, then unfortunately that's outside the domain of this project (I'm not a pyautogui maintainer :).

On the other hand, it is certainly possible that something is wrong in the program; I'm not sure how to fix it though since I don't know what it would be.

**Comment by farvardin** [comment]
@fuzzballcat I've tried from another computer, using the same OS (and same version of qemu), and I don't have this error. 
I don't know what happened, but I suppose I can close this issue for now...
